### ISSUE TITLE
`/api/data/fetch_podcast_feed?podcast_feed=xxx` returns Error 500 `{"detail":"Unable to connect to the database"}`

### ISSUE THREAD

**Issue by forabi** [madeofpendletonwool/PinePods#169]
Running with: Podman (rootless)

```yaml
services:
  pinepods_backend:
    image: madeofpendletonwool/pinepods_backend:latest
    container_name: pinepods_backend
    env_file:
      - pinepods_backend.env
    restart: always
    networks:
      - pinepods
      - caddy

  pinepods_mariadb:
    container_name: pinepods_mariadb
    hostname: pinepods-mariadb
    image: mariadb:11.4.2
    command: --wait_timeout=1800
    userns_mode: keep-id
    user: root
    env_file:
      - ./pinepods_mariadb.env
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: pypods_database
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64*1024*1024;'
    volumes:
      - /media/f/data/docker/volumes/pinepods/mariadb:/var/lib/mysql
    restart: always
    expose:
      - '3306'
    networks:
      - pinepods

  pinepods:
    image: madeofpendletonwool/pinepods:v0.6.0
    container_name: pinepods
    restart: always
    user: root
    userns_mode: keep-id
    ports:
      - "8040:8040"
    env_file:
      - ./pinepods.env
    environment:
      - DB_NAME=pypods_database
      - DB_TYPE=mariadb
      - DB_HOST=pinepods-mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DEBUG_MODE=False
    networks:
      - pinepods
      - caddy
    volumes:
      - /media/f/data/docker/volumes/pinepods/data/downloads:/opt/pinepods/downloads
      - /media/f/data/docker/volumes/pinepods/data/backups:/opt/pinepods/backups
    depends_on:
      - pinepods_mariadb
      - pinepods_backend
networks:
  pinepods: {}

```
