### ISSUE TITLE
When user and pass aren't set in compose have the user set them on first boot

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#352]
Rather than auto generating we should create a component that sets up an admin user on first boot

**Comment by madeofpendletonwool** [comment]
This has just been merged in. You not longer need to set them in compose and the frontend will setup on first boot. So a compose file could look like this at a minimum now. 

```
  post-pinepods:
    image: madeofpendletonwool/pinepods:latest
    ports:
      - "8041:8040"
    environment:
      # Database Vars
      DB_TYPE: postgresql
      DB_HOST: post-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mypass
      DB_NAME: pinepods_database
      # Valkey Settings
      VALKEY_HOST: post-valkey
      VALKEY_PORT: 6379
      # Port Settings
      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: True

```
