### ISSUE TITLE
Issue with Skeptics Guide Feed

### ISSUE THREAD

**Issue by sttrebo** [madeofpendletonwool/PinePods#479]
not sure if it's an issue with the smart playlist or an issue with the podcast, but on the 'quick listens' playlist, 'The Skeptics Guide' podcast has zero duration and seems to list pretty much every podcast episode.  i'm thinking it's an issue with the podcast?

![Image](https://github.com/user-attachments/assets/8ca47ea9-bf58-46ac-901e-900bc1b01481)

**Comment by madeofpendletonwool** [comment]
It's actually almost certainly due to something being strange about that feed. I'll take a look at it.

**Comment by madeofpendletonwool** [comment]
Looked into it. That feed is really weird and nonstandard. 
https://feed.theskepticsguide.org/feed/rss.aspx?feed=sgu

I think it might be the only podcast feed I've ever seen that doesn't include episode durations. It just has the size of the mp3 files in bytes. Really strange. I'm adjusting some fallback options to parse it better

**Comment by DarkVirtue** [comment]
Possibly related - I subscribe to a paid feed through Patreon which also shows 0:00:00 duration for all episodes. It looks like the length is given in the feed as bytes instead of duration (each should be about an hour).

I ran the XML through `yq` to ouput more readable YAML, so here's a couple of episodes with my token redacted:
<details><summary>Patreon RSS feed</summary>

```yaml
      - title: Bonus Content - Wild West
        link: https://www.patreon.com/posts/bonus-content-124746376
        image:
          +@href: https://c10.patreonusercontent.com/4/patreon-media/p/campaign/148317/5a89c7b7340a4385b3c87b7d9f74eba3/eyJoIjoxMDgwLCJ3IjoxMDgwfQ%3D%3D/1.jpg?token-time=2145916800
        description: <p>We made the finest horse wranglin' rope-ridin' cow-paintin' horse-sniffin' range-pissin' cowpokes you ever did lay eyes on.</p>
        enclosure:
          +@url: https://c10.patreonusercontent.com/4/patreon-media/p/post/124746376/97c2671c0d944fba9571d5ff95c1183a/eyJhIjoxLCJwIjoxfQ%3D%3D/1.mp3?token-time=1743811200&token-hash=c3zzUuLGJ16T6cQuYHfxUBDqcBCInzhWWXHfB5eB8rQ%3D
          +@length: "26280657"
          +@type: audio/mpeg
        guid:
          +content: "124746376"
          +@isPermaLink: "false"
        pubDate: Wed, 19 Mar 2025 23:57:31 GMT
      - title: System Mastery 298 - Wild West
        link: https://www.patreon.com/posts/system-mastery-124746298
        image:
          +@href: https://c10.patreonusercontent.com/4/patreon-media/p/campaign/148317/5a89c7b7340a4385b3c87b7d9f74eba3/eyJoIjoxMDgwLCJ3IjoxMDgwfQ%3D%3D/1.jpg?token-time=2145916800
        description: <p>I really hope you're enjoying this string of very old games, we're doing our best to get back into them quickly (ever since I found one of my old box sets fully eaten by bugs and had to fumigate). In this case, it's a game about real old timey cowboys! Like Boot Hill but not TSR!</p>
        enclosure:
          +@url: https://c10.patreonusercontent.com/4/patreon-media/p/post/124746298/209044d02a734e8db9dccea8e7052113/eyJhIjoxLCJwIjoxfQ%3D%3D/1.mp3?token-time=1743811200
          +@length: "73089769"
          +@type: audio/mpeg
        guid:
          +content: "124746298"
          +@isPermaLink: "false"
        pubDate: Wed, 19 Mar 2025 23:54:27 GMT
```
</details>
