### ISSUE TITLE
Admin user at initial install can't log in

### ISSUE THREAD

**Issue by DarkVirtue** [madeofpendletonwool/PinePods#480]
OS: Debian 12
Install: Docker
Browser: Firefox 136.0.2

I'm trying to do a first-time set up of PinePods as per the instructions in the readme. After starting up the containers the main login page loads as expected. However, when I try to log in using the credentials I set using environment vars, the page appears to do nothing for many seconds (internal 30 second timeout?) before returning an error that my credentials are invalid.

While checking the network tab in my dev console, it appears that PinePods is attempting to contact an OIDC server even though I don't (re: can't) have one configured yet.

<details><summary>My compose file</summary>

```yaml
services:
  db:
    container_name: db
    image: postgres:17-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  keystore:
    image: valkey/valkey:alpine
    restart: unless-stopped

  pinepods:
    image: madeofpendletonwool/pinepods:latest
    ports:
      - "127.0.0.1:8040:8040"
    env_file: .env
    environment:
      # Default admin
      USERNAME: admin
      PASSWORD: password
      FULLNAME: Admin Admin
      EMAIL: admin@deb01.test.internal
      # Basic Server Info
      SEARCH_API_URL: 'https://search.pinepods.online/api/search'
      PEOPLE_API_URL: 'https://people.pinepods.online'
      # Database Vars
      DB_TYPE: postgresql
      DB_HOST: db
      VALKEY_HOST: keystore
      VALKEY_PORT: 6379
      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: false
      PUID: 1001
      GUID: 1001
    volumes:
      # Mount the download and backup locations on the server
      - ./downloads:/opt/pinepods/downloads
      - ./backups:/opt/pinepods/backups
    restart: unless-stopped
    depends_on:
      - db
      - keystore
```

</details>

Attached is a screenshot of the aforementioned network output.

![Image](https://github.com/user-attachments/assets/356c2ba1-b1e8-4fee-aa4c-68eebb71128d)
