### ISSUE TITLE
Issues importing OPML files on 0.7.8

### ISSUE THREAD

**Issue by BladeWDR** [madeofpendletonwool/PinePods#527]
Me again! Spun up the new release today but I'm having some issues.

I decided to start fresh and blew away all of my old volumes from when I tested this before.

The web interface comes up, no issues there, but I immediately tried to import an OPML file. It said that it succeeded, but no podcasts actually imported. I'm able to search and add them manually.

I tried this on both Firefox and Chrome in case it was some sort of caching issue.

Adding podcasts manually via the search feature works.

Here's my docker compose file:

```yaml
services:
  db:
    container_name: pinepods-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: pinepods_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PINEPODS_DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pinepods_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  valkey:
    container_name: pinepods-valkey
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"

  pinepods:
    container_name: pinepods-app
    env_file:
      - .env
    image: madeofpendletonwool/pinepods:latest
    ports:
      - "8040:8040"
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      # Basic Server Info
      SEARCH_API_URL: "http://pinepods-api:5000/api/search"
      PEOPLE_API_URL: "https://people.pinepods.online"
      # Default Admin User Information
      USERNAME: ${PINEPODS_ADMIN}
      PASSWORD: ${PINEPODS_ADMIN_PASS}
      FULLNAME: ${PINEPODS_ADMIN_NAME}
      EMAIL: ${PINEPODS_ADMIN_EMAIL}
      # Database Vars
      DB_TYPE: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${PINEPODS_DB_PASS}
      DB_NAME: pinepods_database
      # Valkey Settings
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: true
    volumes:
      - ./backups:/opt/pinepods/backups
      - ./downloads:/opt/pinepods/downloads
    depends_on:
      - db
      - valkey

  pypods-backend:
    image: madeofpendletonwool/pinepods_backend:latest
    container_name: pinepods-api
    env_file:
      - .env
    ports:
      - 5000:5000
    restart: unless-stopped
```

I have debug logging turned on but I'm not seeing anything that stands out to me as the reason for this. I'm happy to share any logs that might be helpful.
