### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by rburettt** [madeofpendletonwool/PinePods#93]
Hi, I'm trying to host Pinepods on 192.168.0.130:8040 with a self hosted API. Here is the Docker compose file I have (it's a different one in the doc and in this repo so I tried my best):

```
version: '3'
services:
  db:
    image: mariadb:latest
    command: --wait_timeout=1800
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: myS3curepass
      MYSQL_DATABASE: pypods_database
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64*1024*1024;'
    volumes:
      - ./sql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  pypods-backend:
    image: madeofpendletonwool/pinepods_backend:latest
    container_name: pypods-be
    environment:
      - API_KEY='MYAPIKEY'
      - API_SECRET='APISERET
    ports:
      - 5004:5000
    restart: unless-stopped
    
    
  pinepods:
    image: madeofpendletonwool/pinepods:latest
    ports:
    # Pinepods Main Port
      - "8040:443"
    environment:
      # Basic Server Info
      SEARCH_API_URL: 'http://192.168.0.130:5004/api/search'
      # Default Admin User Information
      USERNAME: myadminuser01
      PASSWORD: myS3curepass
      FULLNAME: Pinepods Admin
      EMAIL: user@pinepods.online
      # Database Vars
      DB_TYPE: mariadb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: myS3curepass
      DB_NAME: pypods_database
      # Image/Audio Proxy Vars
      HOSTNAME: 192.168.0.130
      PINEPODS_PORT: 8040
      PROXY_PROTOCOL: http
      REVERSE_PROXY: "False"

    volumes:
    # Mount the download and the backup location on the server if you want to. You could mount a nas to the downloads folder or something like that. 
    # The backups directory is used if backups are made on the web version on pinepods. When taking backups on the client version it downloads them locally.
      - ./downloads:/opt/pinepods/downloads
      - ./backups:/opt/pinepods/backups
    depends_on:
      - db
```

Unfortunately when I try accessing Pinepods on 192.168.0.130:8040, this does not work. The log for the container are:
"
INFO:     127.0.0.1:34630 - "GET /api/data/refresh_pods HTTP/1.1" 200 OK
2023-09-15 20:21:44,821 INFO exited: podcast_refresh (exit status 0; expected)
"

If someone could please help me solve this issue, that would be great! The software seems really cool and I'd love to try it.

Many thanks,
Remi
